import ActiveStatus from '@/components/ActiveStatus'
import './globals.css'

import AuthContext from '@/context/AuthContext'
import ToasterContext from '@/context/ToasterContext'
import { Providers } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='dark:bg-zinc-900'>
        <AuthContext>
          <ActiveStatus />
          <ToasterContext />
          <Providers>
            {children}
          </Providers>
        </AuthContext>
      </body>
    </html>
  )
}
